/**
 * ChimeFeedbackPopover Component (Sprint D - Part 4)
 * 
 * Chime-specific feedback sub-component shown when giving negative feedback
 * on a chime-generated message. Lets users choose a rule action:
 * - none: just log the feedback
 * - reduce-frequency: increase the rule's cooldown by 1.5x
 * - disable: disable the rule entirely for this team
 */
import { useState } from 'react'
import type { FeedbackRuleAction } from '@fypai/types'

interface ChimeFeedbackPopoverProps {
  selectedAction: FeedbackRuleAction
  onChange: (action: FeedbackRuleAction) => void
}

const RULE_ACTIONS: { value: FeedbackRuleAction; label: string; description: string }[] = [
  {
    value: 'none',
    label: 'Just log it',
    description: 'Record feedback without changing rule behavior',
  },
  {
    value: 'reduce-frequency',
    label: 'Less frequent',
    description: 'Increase cooldown so this rule triggers less often',
  },
  {
    value: 'disable',
    label: 'Disable rule',
    description: 'Stop this rule from triggering entirely',
  },
]

export const ChimeFeedbackPopover = ({ selectedAction, onChange }: ChimeFeedbackPopoverProps) => {
  return (
    <div className="mt-2 rounded border border-amber-200 bg-amber-50 p-2">
      <p className="text-xs font-medium text-amber-800 mb-1.5">
        ⚙ This was generated by an autonomous rule. What should we do?
      </p>
      <div className="space-y-1">
        {RULE_ACTIONS.map(({ value, label, description }) => (
          <label
            key={value}
            className={`flex items-start space-x-2 rounded px-2 py-1.5 cursor-pointer transition-colors ${
              selectedAction === value
                ? 'bg-amber-100 border border-amber-300'
                : 'hover:bg-amber-100/50 border border-transparent'
            }`}
          >
            <input
              type="radio"
              name="ruleAction"
              value={value}
              checked={selectedAction === value}
              onChange={() => onChange(value)}
              className="mt-0.5"
            />
            <div>
              <span className="text-xs font-medium text-amber-900">{label}</span>
              <p className="text-xs text-amber-700">{description}</p>
            </div>
          </label>
        ))}
      </div>
    </div>
  )
}
