/**
 * CodeOutputCard Component
 * 
 * Displays AI-generated code with syntax highlighting and copy functionality
 */

import { useState } from 'react';
import type { AIInsightDTO } from '../../types';

interface CodeOutputCardProps {
  insight: AIInsightDTO;
  onJumpToSource?: (messageId: string) => void;
}

export const CodeOutputCard = ({ insight, onJumpToSource }: CodeOutputCardProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(insight.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Extract language from code block if present (```language\n...)
  const extractLanguage = (content: string): string | null => {
    const match = content.match(/^```(\w+)/);
    return match ? match[1] : null;
  };

  // Remove code fence markers if present
  const cleanCode = (content: string): string => {
    return content.replace(/^```\w*\n/, '').replace(/\n```$/, '');
  };

  const language = extractLanguage(insight.content);
  const cleanedCode = cleanCode(insight.content);

  return (
    <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-lg shadow-lg border border-gray-700 p-4">
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center space-x-2">
          <svg
            className="w-5 h-5 text-green-400"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
            />
          </svg>
          <span className="font-semibold text-white">💻 Generated Code</span>
          {language && (
            <span className="px-2 py-0.5 bg-gray-700 text-green-400 text-xs font-mono rounded">
              {language}
            </span>
          )}
        </div>
        <div className="flex items-center space-x-2">
          <span className="text-xs text-gray-400">
            {new Date(insight.createdAt).toLocaleTimeString()}
          </span>
          <button
            onClick={handleCopy}
            className="p-1.5 bg-gray-700 hover:bg-gray-600 rounded text-gray-300 hover:text-white transition-colors"
            title="Copy code"
          >
            {copied ? (
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            ) : (
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
            )}
          </button>
        </div>
      </div>

      <div className="bg-gray-950 rounded p-4 overflow-x-auto">
        <pre className="text-sm text-gray-200 font-mono whitespace-pre-wrap">
          <code>{cleanedCode}</code>
        </pre>
      </div>

      {insight.relatedMessageIds?.[0] && onJumpToSource && (
        <button
          onClick={() => onJumpToSource(insight.relatedMessageIds![0])}
          className="mt-3 text-sm text-green-400 hover:text-green-300 font-medium flex items-center space-x-1"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          <span>Jump to source message</span>
        </button>
      )}

      {insight.metadata?.model && (
        <div className="mt-3 pt-3 border-t border-gray-700 text-xs text-gray-400">
          Generated by {insight.metadata.model}
          {insight.metadata.tokensUsed && ` • ${insight.metadata.tokensUsed} tokens`}
          {insight.metadata.prompt && (
            <div className="mt-1 text-gray-500 italic">"{insight.metadata.prompt}"</div>
          )}
        </div>
      )}
    </div>
  );
};
