import type { ReactNode } from 'react'
import type { AIInsightDTO } from '../../types'

interface InsightFrameProps {
  insight: AIInsightDTO
  title: string
  icon: ReactNode
  containerClassName: string
  titleClassName: string
  timeClassName: string
  content: ReactNode
  onJumpToSource?: (messageId: string) => void
  jumpButtonClassName?: string
  metadataClassName?: string
}

export const InsightFrame = ({
  insight,
  title,
  icon,
  containerClassName,
  titleClassName,
  timeClassName,
  content,
  onJumpToSource,
  jumpButtonClassName = 'mt-3 text-sm text-blue-700 hover:text-blue-900 font-medium flex items-center space-x-1',
  metadataClassName = 'mt-3 pt-3 border-t border-gray-100 text-xs text-gray-600',
}: InsightFrameProps) => {
  return (
    <div className={containerClassName}>
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center space-x-2">
          {icon}
          <span className={`${titleClassName} leading-5`}>{title}</span>
        </div>
        <span className={`${timeClassName} whitespace-nowrap`}>{new Date(insight.createdAt).toLocaleTimeString()}</span>
      </div>

      {insight.metadata?.chimeRuleName && (
        <div className="mb-3">
          <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-purple-100 text-purple-700 border border-purple-200">
            ⚙️ Rule: {insight.metadata.chimeRuleName}
          </span>
        </div>
      )}

      {content}

      {insight.relatedMessageIds?.[0] && onJumpToSource && (
        <button
          onClick={() => onJumpToSource(insight.relatedMessageIds![0])}
          className={jumpButtonClassName}
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          <span>Jump to source message</span>
        </button>
      )}

      {(insight.metadata?.model || insight.metadata?.prompt) && (
        <div className={metadataClassName}>
          {insight.metadata?.model && (
            <div>
              Generated by {insight.metadata.model}
              {insight.metadata.tokensUsed && ` • ${insight.metadata.tokensUsed} tokens`}
            </div>
          )}
          {insight.metadata?.prompt && (
            <div className="mt-1 italic">"{insight.metadata.prompt}"</div>
          )}
        </div>
      )}
    </div>
  )
}
