/**
 * SummaryCard Component
 * 
 * Displays AI-generated conversation summaries with structured formatting
 * Shows key points, decisions, and action items with markdown rendering
 */

import type { MessageDTO } from '../../types';
import ReactMarkdown from 'react-markdown';

interface SummaryCardProps {
  message: MessageDTO;
  onJumpToSource?: (messageId: string) => void;
}

export const SummaryCard = ({ message, onJumpToSource }: SummaryCardProps) => {
  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg shadow-sm border border-blue-200 p-4">
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center space-x-2">
          <svg
            className="w-5 h-5 text-blue-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          <span className="font-semibold text-blue-900">📊 Conversation Summary</span>
        </div>
        <span className="text-xs text-blue-700">
          {new Date(message.createdAt).toLocaleTimeString()}
        </span>
      </div>

      <div className="prose prose-sm prose-blue max-w-none text-gray-800">
        <ReactMarkdown
          components={{
            // Style headers
            h1: ({ children }) => <h1 className="text-xl font-bold text-blue-900 mt-4 mb-2">{children}</h1>,
            h2: ({ children }) => <h2 className="text-lg font-bold text-blue-800 mt-3 mb-2">{children}</h2>,
            h3: ({ children }) => <h3 className="text-base font-semibold text-blue-700 mt-2 mb-1">{children}</h3>,
            // Style lists
            ul: ({ children }) => <ul className="list-disc list-inside space-y-1 my-2">{children}</ul>,
            ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 my-2">{children}</ol>,
            // Style paragraphs
            p: ({ children }) => <p className="my-2 leading-relaxed">{children}</p>,
            // Style bold and italic
            strong: ({ children }) => <strong className="font-semibold text-blue-900">{children}</strong>,
            em: ({ children }) => <em className="italic text-gray-700">{children}</em>,
            // Style code
            code: ({ children }) => <code className="bg-blue-100 text-blue-800 px-1 py-0.5 rounded text-sm">{children}</code>,
          }}
        >
          {message.content}
        </ReactMarkdown>
      </div>

      {message.metadata?.parentMessageId && onJumpToSource && (
        <button
          onClick={() => onJumpToSource(message.metadata!.parentMessageId!)}
          className="mt-3 text-sm text-blue-700 hover:text-blue-900 font-medium flex items-center space-x-1"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          <span>Jump to source message</span>
        </button>
      )}

      {message.metadata?.model && (
        <div className="mt-3 pt-3 border-t border-blue-100 text-xs text-blue-600">
          Generated by {message.metadata.model}
          {message.metadata.tokensUsed && ` • ${message.metadata.tokensUsed} tokens`}
          {message.metadata.prompt && (
            <div className="mt-1 text-blue-500 italic">"{message.metadata.prompt}"</div>
          )}
        </div>
      )}
    </div>
  );
};
